services:
  app:
    container_name: ocr-api
    image: ghcr.io/unisa-groups/ocr-api:sha-ffed0ac
    restart: always
    ports:
      - "30000:30000"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
