services:
  squint-ocr:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: squint_ocr_service
    restart: always
    ports:
      - "30000:30000"
    volumes:
      - ./config.json:/app/config.json
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M